# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'
timezone: Asia/Seoul
future: true

# Website info
name: 'hwaseongglobalcenter'
description: 'hwaseongglobalcenter'

short_url: 'hwaseongglobalcenter.github.io'
google_analytics: ''
disqus: ''
baseurl: "/"

# Permalinks
permalink: /:title

# gems and other configs
plugins: [jekyll-paginate]

# Settings for deploy
safe: false
lsi: false
username: hwaseongglobalcenter
repo: hwaseongglobalcenter.github.io
branch: main
production_url: https://hwaseongglobalcenter.github.io
source_url: https://github.com/hwaseongglobalcenter/hwaseongglobalcenter.github.io

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
